export { CurvedSidebar } from './CurvedSidebar'
export { ClassroomHeader } from './ClassroomHeader'
export { ParticipantStrip } from './ParticipantStrip'
export { MainWorkspace } from './MainWorkspace'
export { CommunicationPanel } from './CommunicationPanel'
export { FloatingControlBar } from './FloatingControlBar'
export { ClassroomInterior as ClassroomInteriorNew } from './ClassroomInteriorNew'
export { ClassroomAssignmentManager } from './ClassroomAssignmentManager'

// Re-export existing components
export { ParticipantTile } from './participant-tile'
export { MonitorStrip } from './monitor-strip'
export { SidePanel } from './side-panel'
export { WhiteboardArea } from './whiteboard-area'
export { TimerPopup } from './timer-popup'
export { ComponentModal } from './component-modal'
export { MonkeyBot } from './monkey-bot'
export { EmojiReaction } from './emoji-reaction'
export { RecordingIndicator } from './recording-indicator'
export { TeacherPanel } from './teacher-panel'
export { PollWidget } from './poll-widget'
export { BreakoutManager } from './breakout-manager'
export { ResourceBrowser } from './resource-browser'
export { ScreenStage } from './screen-stage'
export { FloatingMonitor } from './floating-monitor'